version: '2'

services:
  item-db:
    image: mongo:3
    volumes:
      - app-db:/data/db

  item-app:
    image: happybadila/item-app:v1
    ports:
      - "3000:80"
    depends_on:
      - item-db
    restart: always

volumes:
  app-db:
